[tool.poetry]
name = "payment-service"
version = "0.1.0"
description = "Async payment processing microservice"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
aiohttp = ">=3.14.1"
alembic = ">=1.18.4"
asyncpg = ">=0.31.0"
dishka = ">=1.10.1"
dishka-faststream = ">=0.7.0"
fastapi = ">=0.137.1"
faststream = { version = ">=0.7.1", extras = ["rabbit"] }
pydantic = ">=2.13.4"
pydantic-settings = ">=2.14.1"
pyyaml = ">=6.0.3"
sqlalchemy = ">=2.0.51"
uvicorn = ">=0.49.0"

[tool.poetry.group.dev.dependencies]
aiosqlite = ">=0.22.1"
pytest = ">=9.1.1"
pytest-asyncio = ">=1.4.0"
ruff = ">=0.15.18"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
lint.select = ["E", "F", "I", "W", "DJ"]
lint.ignore = []

[tool.ruff.format]
preview = true
indent-style = "space"
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = ["src"]
log_cli = false
log_level = "INFO"
asyncio_mode = "auto"
